/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrimaryAppRouteImport } from './routes/primary/_app'
import { Route as PrimaryLoginRouteImport } from './routes/primary/login'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as PrimaryAppAuditRouteImport } from './routes/primary/_app/audit'
import { Route as PrimaryAppDashboardRouteImport } from './routes/primary/_app/dashboard'
import { Route as PrimaryAppLandRecordsRouteImport } from './routes/primary/_app/land-records'
import { Route as PrimaryAppUploadRouteImport } from './routes/primary/_app/upload'
import { Route as PrimaryAppVerificationRouteImport } from './routes/primary/_app/verification'
import { Route as SearchRecordIdRouteImport } from './routes/search/record.$id'
import { Route as PrimaryAppOcrDocumentIdRouteImport } from './routes/primary/_app/ocr.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaryAppRoute = PrimaryAppRouteImport.update({
  id: '/primary/_app',
  path: '/primary',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaryLoginRoute = PrimaryLoginRouteImport.update({
  id: '/primary/login',
  path: '/primary/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaryAppAuditRoute = PrimaryAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PrimaryAppRoute,
} as any)
const PrimaryAppDashboardRoute = PrimaryAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrimaryAppRoute,
} as any)
const PrimaryAppLandRecordsRoute = PrimaryAppLandRecordsRouteImport.update({
  id: '/land-records',
  path: '/land-records',
  getParentRoute: () => PrimaryAppRoute,
} as any)
const PrimaryAppUploadRoute = PrimaryAppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PrimaryAppRoute,
} as any)
const PrimaryAppVerificationRoute = PrimaryAppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => PrimaryAppRoute,
} as any)
const SearchRecordIdRoute = SearchRecordIdRouteImport.update({
  id: '/search/record/$id',
  path: '/search/record/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaryAppOcrDocumentIdRoute = PrimaryAppOcrDocumentIdRouteImport.update({
  id: '/ocr/$documentId',
  path: '/ocr/$documentId',
  getParentRoute: () => PrimaryAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/primary': typeof PrimaryAppRouteWithChildren
  '/primary/login': typeof PrimaryLoginRoute
  '/search/': typeof SearchIndexRoute
  '/primary/audit': typeof PrimaryAppAuditRoute
  '/primary/dashboard': typeof PrimaryAppDashboardRoute
  '/primary/land-records': typeof PrimaryAppLandRecordsRoute
  '/primary/upload': typeof PrimaryAppUploadRoute
  '/primary/verification': typeof PrimaryAppVerificationRoute
  '/search/record/$id': typeof SearchRecordIdRoute
  '/primary/ocr/$documentId': typeof PrimaryAppOcrDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/primary': typeof PrimaryAppRouteWithChildren
  '/primary/login': typeof PrimaryLoginRoute
  '/search': typeof SearchIndexRoute
  '/primary/audit': typeof PrimaryAppAuditRoute
  '/primary/dashboard': typeof PrimaryAppDashboardRoute
  '/primary/land-records': typeof PrimaryAppLandRecordsRoute
  '/primary/upload': typeof PrimaryAppUploadRoute
  '/primary/verification': typeof PrimaryAppVerificationRoute
  '/search/record/$id': typeof SearchRecordIdRoute
  '/primary/ocr/$documentId': typeof PrimaryAppOcrDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/primary/_app': typeof PrimaryAppRouteWithChildren
  '/primary/login': typeof PrimaryLoginRoute
  '/search/': typeof SearchIndexRoute
  '/primary/_app/audit': typeof PrimaryAppAuditRoute
  '/primary/_app/dashboard': typeof PrimaryAppDashboardRoute
  '/primary/_app/land-records': typeof PrimaryAppLandRecordsRoute
  '/primary/_app/upload': typeof PrimaryAppUploadRoute
  '/primary/_app/verification': typeof PrimaryAppVerificationRoute
  '/search/record/$id': typeof SearchRecordIdRoute
  '/primary/_app/ocr/$documentId': typeof PrimaryAppOcrDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/help'
    | '/how-it-works'
    | '/primary'
    | '/primary/login'
    | '/search/'
    | '/primary/audit'
    | '/primary/dashboard'
    | '/primary/land-records'
    | '/primary/upload'
    | '/primary/verification'
    | '/search/record/$id'
    | '/primary/ocr/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/how-it-works'
    | '/primary'
    | '/primary/login'
    | '/search'
    | '/primary/audit'
    | '/primary/dashboard'
    | '/primary/land-records'
    | '/primary/upload'
    | '/primary/verification'
    | '/search/record/$id'
    | '/primary/ocr/$documentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/help'
    | '/how-it-works'
    | '/primary/_app'
    | '/primary/login'
    | '/search/'
    | '/primary/_app/audit'
    | '/primary/_app/dashboard'
    | '/primary/_app/land-records'
    | '/primary/_app/upload'
    | '/primary/_app/verification'
    | '/search/record/$id'
    | '/primary/_app/ocr/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrimaryAppRoute: typeof PrimaryAppRouteWithChildren
  PrimaryLoginRoute: typeof PrimaryLoginRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SearchRecordIdRoute: typeof SearchRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary/_app': {
      id: '/primary/_app'
      path: '/primary'
      fullPath: '/primary'
      preLoaderRoute: typeof PrimaryAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary/login': {
      id: '/primary/login'
      path: '/primary/login'
      fullPath: '/primary/login'
      preLoaderRoute: typeof PrimaryLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary/_app/audit': {
      id: '/primary/_app/audit'
      path: '/audit'
      fullPath: '/primary/audit'
      preLoaderRoute: typeof PrimaryAppAuditRouteImport
      parentRoute: typeof PrimaryAppRoute
    }
    '/primary/_app/dashboard': {
      id: '/primary/_app/dashboard'
      path: '/dashboard'
      fullPath: '/primary/dashboard'
      preLoaderRoute: typeof PrimaryAppDashboardRouteImport
      parentRoute: typeof PrimaryAppRoute
    }
    '/primary/_app/land-records': {
      id: '/primary/_app/land-records'
      path: '/land-records'
      fullPath: '/primary/land-records'
      preLoaderRoute: typeof PrimaryAppLandRecordsRouteImport
      parentRoute: typeof PrimaryAppRoute
    }
    '/primary/_app/upload': {
      id: '/primary/_app/upload'
      path: '/upload'
      fullPath: '/primary/upload'
      preLoaderRoute: typeof PrimaryAppUploadRouteImport
      parentRoute: typeof PrimaryAppRoute
    }
    '/primary/_app/verification': {
      id: '/primary/_app/verification'
      path: '/verification'
      fullPath: '/primary/verification'
      preLoaderRoute: typeof PrimaryAppVerificationRouteImport
      parentRoute: typeof PrimaryAppRoute
    }
    '/search/record/$id': {
      id: '/search/record/$id'
      path: '/search/record/$id'
      fullPath: '/search/record/$id'
      preLoaderRoute: typeof SearchRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary/_app/ocr/$documentId': {
      id: '/primary/_app/ocr/$documentId'
      path: '/ocr/$documentId'
      fullPath: '/primary/ocr/$documentId'
      preLoaderRoute: typeof PrimaryAppOcrDocumentIdRouteImport
      parentRoute: typeof PrimaryAppRoute
    }
  }
}

interface PrimaryAppRouteChildren {
  PrimaryAppAuditRoute: typeof PrimaryAppAuditRoute
  PrimaryAppDashboardRoute: typeof PrimaryAppDashboardRoute
  PrimaryAppLandRecordsRoute: typeof PrimaryAppLandRecordsRoute
  PrimaryAppUploadRoute: typeof PrimaryAppUploadRoute
  PrimaryAppVerificationRoute: typeof PrimaryAppVerificationRoute
  PrimaryAppOcrDocumentIdRoute: typeof PrimaryAppOcrDocumentIdRoute
}

const PrimaryAppRouteChildren: PrimaryAppRouteChildren = {
  PrimaryAppAuditRoute: PrimaryAppAuditRoute,
  PrimaryAppDashboardRoute: PrimaryAppDashboardRoute,
  PrimaryAppLandRecordsRoute: PrimaryAppLandRecordsRoute,
  PrimaryAppUploadRoute: PrimaryAppUploadRoute,
  PrimaryAppVerificationRoute: PrimaryAppVerificationRoute,
  PrimaryAppOcrDocumentIdRoute: PrimaryAppOcrDocumentIdRoute,
}

const PrimaryAppRouteWithChildren = PrimaryAppRoute._addFileChildren(
  PrimaryAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrimaryAppRoute: PrimaryAppRouteWithChildren,
  PrimaryLoginRoute: PrimaryLoginRoute,
  SearchIndexRoute: SearchIndexRoute,
  SearchRecordIdRoute: SearchRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
